### ISSUE TITLE
Move project to pagarme organization

### ISSUE THREAD

**Issue by lucianopf** [pagarme/the-office#45]
# Description

Even though this project has been built outside working hours or the companies expectation this project is targeted to be mainly used by the Stone.co group which Pagar.me belongs to and because of that it makes totally sense to move this project to its Github organisation.

In order to do that we'll need to change a couple settings, mainly related to deployment.

Right now the repo/project is using [Zeit Integration](https://zeit.co/github) in order to move this into Pagarme org we'll need either to setup the Zeit integration OR to define a new ci/cd method, most probably using CircleCI.

# Tasks

- [x] Discuss the best method to interact with a continuous deployment method
- [x] Setup the new CI/CD
- [x] Move to org
- [x] Setup contributors

**Comment by lucianopf** [comment]
Finished. (forgot to close this one 😬 )
